// One-time starter flashcards for the IT Project Management course.
// Applied on server start (see seedFlashcards in server.js) only to lessons
// that match by id AND title and still have no flashcards, and only once —
// a settings flag stops it from re-adding cards an admin later deletes.

const c = (term, def) => ({ term, def });

module.exports = {
  settingsKey: 'seed_flashcards_itpm_v1',
  courseSlug: 'it-pm',
  lessons: [
    { id: 15, title: 'Open Class', cards: [
      c('Project', 'A temporary effort with a defined start and end, undertaken to create a unique product, service or result.'),
      c('Operations', 'Ongoing, repetitive work that keeps the business running — unlike a project, it has no planned end.'),
      c('Project management', 'Applying knowledge, skills, tools and techniques to project activities so the project meets its requirements.'),
      c('Project manager', 'The person accountable for planning, coordinating and delivering the project and keeping stakeholders aligned.'),
      c('Stakeholder', 'Anyone who affects, or is affected by, the project — sponsors, users, team members, customers, regulators.'),
      c('Triple constraint (Iron triangle)', 'Scope, time and cost: changing one affects the others, and together they shape quality.'),
      c('Deliverable', 'Any tangible or measurable output a project must produce — a document, feature, report or product.'),
      c('Methodology', 'A defined set of practices, roles and steps for running a project, such as Waterfall, Scrum or Kanban.'),
    ]},
    { id: 31, title: 'IT Project Management Intro', cards: [
      c('IT project', 'A project whose main output is software, infrastructure, data or another technology change.'),
      c('Frederick Taylor', 'Founder of "scientific management" — broke manual labour into measurable, time-studied tasks to improve efficiency.'),
      c('Henry Gantt', 'Created the Gantt chart (c. 1910s), a bar chart showing tasks against a timeline.'),
      c('Gantt chart', 'A timeline view of tasks as horizontal bars, showing start/end dates, duration and dependencies.'),
      c('PMI / PMBOK', 'Project Management Institute (founded 1969) and its Body of Knowledge — a widely used PM standard.'),
      c('Agile Manifesto (2001)', 'Four values and twelve principles favouring individuals, working software, customer collaboration and responding to change.'),
      c('Project life cycle', 'The phases a project passes through: initiation, planning, execution, monitoring & control, closing.'),
      c('AI productivity assistant', 'An AI tool that helps with everyday PM work — drafting status emails, summarising documents and meeting notes.'),
      c('Project sponsor', 'The senior person or group who funds the project, champions it and makes key business decisions.'),
    ]},
    { id: 32, title: 'Waterfall vs. Agile', cards: [
      c('Waterfall', 'A sequential model: each phase is finished before the next starts. Best for fixed scope, fixed deadline, low uncertainty.'),
      c('Waterfall stages', 'Requirements → Design → Implementation → Verification → Maintenance, done strictly in order.'),
      c('Agile', 'An iterative approach delivering working increments in short cycles and adapting to feedback and change.'),
      c('Late requirements defect (Waterfall)', 'A flaw found late (e.g. in Verification) usually means going back to earlier phases — costly rework and delay.'),
      c('Iteration', 'A short, fixed time-box in which a team plans, builds and reviews a usable piece of the product.'),
      c('When to choose Waterfall', 'Regulatory or contract-driven projects with stable, well-known requirements and a hard deadline.'),
      c('When to choose Agile', 'Projects with changing or unclear requirements where early, frequent feedback adds value.'),
      c('Hybrid approach', 'Mixing both: e.g. Waterfall-style planning and governance with Agile delivery inside phases.'),
      c('Cost of change curve', 'The later a change or defect is found, the more expensive it is to fix — especially in sequential models.'),
    ]},
    { id: 33, title: 'Time Management', cards: [
      c('PERT estimate', 'Weighted average of three estimates: (Optimistic + 4 × Most likely + Pessimistic) ÷ 6.'),
      c('Three-point estimating', 'Estimating with optimistic, most-likely and pessimistic values to account for uncertainty.'),
      c('Buffer (contingency)', 'Extra time added to an estimate or schedule to absorb risks and surprises.'),
      c('Critical path', 'The longest chain of dependent tasks — it sets the shortest possible project duration. Delay here delays the project.'),
      c('Float (slack)', 'How long a task can be delayed without delaying the project. Critical-path tasks have zero float.'),
      c('Milestone', 'A significant point or event in the schedule with zero duration, e.g. "Design approved".'),
      c('Dependency (Finish-to-Start)', 'The most common link: task B cannot start until task A finishes.'),
      c('Time-boxing', 'Giving an activity a fixed, non-extendable amount of time, then delivering what is done.'),
      c('AI scheduling assistant', 'A tool that uses AI to plan calendars, prioritise tasks or protect focus time automatically.'),
    ]},
    { id: 34, title: 'Resource & Scope Management', cards: [
      c('Scope', 'Everything the project will deliver — and, just as important, what it will not.'),
      c('Scope creep', 'Uncontrolled growth of scope without matching changes to time, budget or resources.'),
      c('WBS (Work Breakdown Structure)', 'A hierarchical breakdown of the total scope into smaller, manageable deliverables and work packages.'),
      c('Planned Value (PV)', 'The budgeted cost of the work scheduled to be done by now.'),
      c('Earned Value (EV)', 'The budgeted value of work actually completed: EV = % complete × budget (e.g. 25% of $80,000 = $20,000).'),
      c('Actual Cost (AC)', 'What has actually been spent on the work completed so far.'),
      c('CPI (Cost Performance Index)', 'CPI = EV ÷ AC. Below 1 means over budget (e.g. 60k ÷ 75k = 0.8); above 1 means under budget.'),
      c('SPI (Schedule Performance Index)', 'SPI = EV ÷ PV. Below 1 means behind schedule; above 1 means ahead.'),
      c('Relative sizing (T-shirt / vehicles)', 'Estimating stories by comparison (bike, car, bus…) — a "bus" story is much larger than a "car" story.'),
      c('Resource levelling', 'Adjusting the schedule so no person or resource is overloaded at any time.'),
    ]},
    { id: 35, title: 'Risk Management', cards: [
      c('Risk', 'An uncertain event that, if it happens, has a positive (opportunity) or negative (threat) effect on the project.'),
      c('Issue', 'A risk that has already happened and now needs action.'),
      c('EMV (Expected Monetary Value)', 'EMV = probability × impact. E.g. 30% × $50,000 = $15,000.'),
      c('Risk exposure', 'Probability × severity (impact). E.g. 25% × $200,000 = $50,000.'),
      c('ROI (Return on Investment)', 'ROI = (Benefit − Cost) ÷ Cost × 100%. E.g. ($20,000 − $8,000) ÷ $8,000 = 150%.'),
      c('Risk register', 'A log of identified risks with probability, impact, owner, response and status.'),
      c('Probability–impact matrix', 'A grid that rates risks by likelihood and impact to decide which to handle first.'),
      c('Risk responses (threats)', 'Avoid, Transfer, Mitigate, Accept.'),
      c('Risk owner', 'The person responsible for monitoring a risk and carrying out its response.'),
      c('Contingency reserve', 'Time or money set aside for known risks that may occur.'),
    ]},
    { id: 36, title: 'Scrum Framework', cards: [
      c('Scrum', 'A lightweight Agile framework where a small team delivers value in fixed-length Sprints.'),
      c('Product Owner', 'Maximises product value; owns and orders the Product Backlog and decides what gets built.'),
      c('Scrum Master', 'Coaches the team in Scrum, removes impediments and helps resolve blocks — e.g. when the PO is unavailable.'),
      c('Developers', 'The people who build the Increment each Sprint and own the Sprint Backlog.'),
      c('Scrum flow', 'Product Backlog → Sprint Planning → Sprint Backlog → Sprint (Daily Scrums) → Increment → Review → Retrospective.'),
      c('Definition of Ready (DoR)', 'Criteria a backlog item must meet before the team pulls it into a Sprint — sits between Product Backlog and Sprint Backlog.'),
      c('Definition of Done (DoD)', 'The shared quality checklist an item must meet to count as part of the Increment.'),
      c('Daily Scrum', 'A 15-minute daily event for Developers to inspect progress toward the Sprint Goal and adapt the plan.'),
      c('Sprint Review', 'Inspecting the Increment with stakeholders at the end of the Sprint and adapting the Product Backlog.'),
      c('Sprint Retrospective', 'The team reflects on how it worked and picks improvements for the next Sprint.'),
    ]},
    { id: 37, title: 'Sprint Planning', cards: [
      c('Sprint Planning', 'The event that starts a Sprint: the team agrees why (Sprint Goal), what (items) and how (tasks).'),
      c('Sprint Goal', 'A single objective for the Sprint that gives the team focus and flexibility.'),
      c('Part 1 — "What"', 'The team selects backlog items it can deliver, guided by the Product Owner and the Sprint Goal.'),
      c('Part 2 — "How"', 'Developers break selected items into tasks, typically small — around a day of work or less.'),
      c('Capacity', 'People × hours per day × Sprint days × focus factor. E.g. 6 × 6 × 9 × 75% = 243 hours.'),
      c('Focus factor', 'The share of time actually available for Sprint work after meetings, support and interruptions.'),
      c('Overcommitting fix', 'Plan using historical velocity and real capacity, not wishes — commit to what past data supports.'),
      c('Story points', 'A relative unit for estimating effort, complexity and uncertainty of backlog items.'),
      c('Planning Poker', 'Team members estimate simultaneously with cards, then discuss differences to reach consensus.'),
    ]},
    { id: 38, title: 'Scrum Metrics & Charts', cards: [
      c('Velocity', 'Story points completed per Sprint. Average velocity = total points ÷ number of Sprints (12+9+15+16 = 52 ÷ 4 = 13).'),
      c('Lead time', 'From when an item is created/requested to when it is delivered. E.g. created Day 2, delivered Day 30 = 28 days.'),
      c('Cycle time', 'From when work actually starts to delivery. E.g. started Day 9, delivered Day 30 = 21 days.'),
      c('Burndown chart', 'Shows remaining work over time in a Sprint; ideally trends down to zero by the end.'),
      c('Burnup chart', 'Shows completed work rising toward total scope — also makes scope changes visible.'),
      c('Throughput', 'Number of items finished per period of time (e.g. per week).'),
      c('Cumulative Flow Diagram (CFD)', 'Stacked bands showing how many items are in each state over time; widening bands reveal bottlenecks.'),
      c('Sprint commitment reliability', 'Completed points ÷ committed points — how predictable the team\'s planning is.'),
      c('Escaped defects', 'Bugs found after release — a quality signal for the Definition of Done.'),
    ]},
    { id: 43, title: 'Technical lesson 1- Scrum Simulation', cards: [
      c('Simulation goal', 'Practise a full Scrum cycle hands-on: backlog, planning, daily work, review and retrospective.'),
      c('Product Backlog (in practice)', 'An ordered list of user stories the Product Owner prioritises before planning.'),
      c('User story', '"As a <user>, I want <goal>, so that <benefit>" — a small piece of value told from the user\'s view.'),
      c('Acceptance criteria', 'Conditions a story must satisfy to be accepted by the Product Owner.'),
      c('Task board', 'Columns such as To do / In progress / Done that make Sprint work visible to everyone.'),
      c('Impediment', 'Anything blocking the team — raised in the Daily Scrum and removed with help from the Scrum Master.'),
      c('Increment', 'The sum of all Done items at the end of the Sprint — usable and potentially releasable.'),
      c('Start / Stop / Continue', 'A simple retrospective format: what to start doing, stop doing, and keep doing.'),
    ]},
    { id: 39, title: 'Kanban Method', cards: [
      c('Kanban', 'A flow-based method: visualise work, limit work in progress and improve flow continuously — no fixed Sprints.'),
      c('When to use Kanban', 'Continuous, unbatched work with changing priorities — e.g. support, operations, maintenance teams.'),
      c('Kanban board', 'Columns representing workflow stages; cards move left to right as work progresses.'),
      c('WIP limit', 'The maximum number of items allowed in a column at once — e.g. "Testing (2)" means no 3rd item may enter.'),
      c('Pull system', 'New work is pulled into a stage only when there is capacity, instead of being pushed in.'),
      c('Service Delivery principles', 'Understand and focus on customer needs; manage the work, let people self-organise; evolve policies to improve outcomes.'),
      c('Change Management principles', 'Start with what you do now; agree to pursue evolutionary change; encourage acts of leadership at every level.'),
      c('Explicit policies', 'Clearly written rules for how work moves — e.g. what "Done" means for each column.'),
      c('Classes of service', 'Different handling rules by urgency/type, such as Expedite, Fixed date, Standard, Intangible.'),
    ]},
    { id: 40, title: 'Kanban 2 (WIP & Continuous Improvement)', cards: [
      c("Little's Law", 'Average cycle time = WIP ÷ throughput. E.g. 24 items ÷ 6 per week = 4 weeks.'),
      c('Process efficiency (flow efficiency)', 'Value-added time ÷ total time. E.g. VA 20 days, NVA 5 days → 20 ÷ 25 = 80%.'),
      c('Value-added (VA) time', 'Time spent actively working on an item in a way the customer values.'),
      c('Non-value-added (NVA) time', 'Waiting, hand-offs, rework — time the item spends without progress.'),
      c('Setting total WIP', 'Base it on team size and real capacity (e.g. people × efficiency) and adjust from observed flow.'),
      c('Bottleneck', 'The stage with the least capacity, where work piles up and slows the whole system.'),
      c('Kaizen', 'Continuous improvement through small, frequent changes.'),
      c('Feedback loops (cadences)', 'Regular reviews such as replenishment, delivery planning, service delivery review and retrospectives.'),
      c('Blocked item', 'A card that cannot progress; it should be flagged visibly and swarmed to unblock.'),
    ]},
    { id: 44, title: 'Technical lesson 2- KanBan Simulation', cards: [
      c('Simulation goal', 'See how WIP limits, pull and bottlenecks affect flow by running work through a Kanban board.'),
      c('Swarming', 'Team members help on a stuck or bottleneck item instead of starting new work.'),
      c('Stop starting, start finishing', 'The Kanban mantra: finish work in progress before pulling more.'),
      c('Queue (buffer) column', 'A "ready" or "waiting" column between stages that makes waiting time visible.'),
      c('Expedite lane', 'A special lane for urgent items, usually with a WIP limit of one.'),
      c('Flow metrics in practice', 'Track throughput, cycle time and WIP each round to see the effect of your changes.'),
      c('Replenishment meeting', 'Deciding which items enter the board next, based on priority and capacity.'),
    ]},
    { id: 41, title: 'Other Agile Methods (XP, Lean, SAFe)', cards: [
      c('XP (Extreme Programming)', 'An Agile method focused on engineering excellence: pairing, TDD, continuous integration, small releases.'),
      c('Pair programming', 'Two developers share one workstation — one writes code, the other reviews in real time; they switch often.'),
      c('TDD (Test-Driven Development)', 'Write a failing test first, then the code to pass it, then refactor (Red → Green → Refactor).'),
      c('Continuous integration', 'Merging and testing code frequently (many times a day) to catch problems early.'),
      c('Lean', 'Maximise customer value while eliminating waste; optimise the whole flow.'),
      c('Lean wastes in software', 'Partially done work, extra features, relearning, hand-offs, delays, task switching, defects.'),
      c('Extra features (waste)', 'Building things nobody asked for — e.g. an unused, speculatively built reporting engine.'),
      c('SAFe (Scaled Agile Framework)', 'A framework for running Agile across many teams in large organisations.'),
      c('Agile Release Train (ART)', 'In SAFe, a long-lived team of Agile teams that plans and delivers together.'),
      c('PI Planning', 'In SAFe, a regular large planning event where all teams on the train align on objectives for the next Program Increment.'),
    ]},
    { id: 42, title: 'Project Criteria & Documentation', cards: [
      c('Definition of Ready (DoR)', 'A story is ready only when it has clear criteria, an estimate AND team agreement that it can be started.'),
      c('Definition of Done (DoD)', 'A feature is done only when ALL criteria are met — e.g. passing tests is not enough without PO review if DoD requires it.'),
      c('Acceptance criteria', 'Specific conditions a feature must meet to be accepted by the Product Owner or customer.'),
      c('Deployment / release readiness', 'Criteria for going live — e.g. testing done, rollback plan in place, stakeholders informed.'),
      c('Rollback plan', 'A documented way to undo a release quickly if something goes wrong — required for release readiness.'),
      c('Project charter', 'The document that formally authorises the project and states its goals, scope, sponsor and high-level plan.'),
      c('Requirements document', 'Describes what the solution must do (functional) and how well (non-functional).'),
      c('Status report', 'Regular update on progress, risks, issues and next steps for stakeholders.'),
      c('Lessons learned', 'Recorded insights from a project or phase to improve future work.'),
    ]},
    { id: 45, title: 'Claude in Project Management', cards: [
      c('Claude', 'An AI assistant by Anthropic that can help PMs with writing, analysis, planning and summarising.'),
      c('Prompt', 'The instruction you give the AI. Clear context, goal and desired format give better results.'),
      c('Good PM uses of AI', 'Drafting status reports and emails, summarising meetings, writing user stories, brainstorming risks.'),
      c('Context', 'Background you give the AI (project goal, audience, constraints) so its answer fits your situation.'),
      c('Human review', 'Always check AI output for accuracy before sharing — the PM stays accountable for decisions.'),
      c('Data privacy', 'Do not paste confidential or personal data into AI tools unless your organisation allows it.'),
      c('Iterating on output', 'Ask follow-up questions to refine — e.g. "make it shorter", "add a risks section", "use a table".'),
    ]},
  ],
};
